# Setup
theme:        jekyll-theme-cayman
title:        "Samples for MOS"
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Wanyi
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
